### ISSUE TITLE
gender color may be incorrect for "unknown value" in co-author graphs

### ISSUE THREAD

**Issue by egonw** [fnielsen/scholia#680] opened 2019-04-22 08:58 UTC
Perhaps new, but there are "unknown value" genders in Wikidata:

![image](https://user-images.githubusercontent.com/26721/56492863-59e94f80-64ed-11e9-9153-652307282b18.png)

However, this results in a colored note in the co-author graphs:

![image](https://user-images.githubusercontent.com/26721/56492901-7d13ff00-64ed-11e9-8db4-4f0b48b61a67.png)

**Comment by fnielsen** [comment] 2019-04-23 13:37
This is a duplicate of #668

**Closed by fnielsen** 2019-04-23 13:37 UTC
Labels: P21-gender, aspects, bug

**Comment by egonw** [comment] 2019-04-23 13:41
Oh, sorry. I had looked (IIRC), but clearly missed this one.
