### ISSUE TITLE
arXiv to QuickStatements seems stalled

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#1148] opened 2020-06-06 21:19 UTC
e.g. 
https://tools.wmflabs.org/scholia/arxiv-to-quickstatements?arxiv=2004.04463 - hitting the "extract metadata" button does not yield any results

**Comment by fnielsen** [comment] 2020-06-08 23:54
Duplicate of #1059

**Closed by fnielsen** 2020-06-08 23:54 UTC
Labels: bug
