### ISSUE TITLE
"Citations per year" shows self-citations twice

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#478] opened 2018-08-25 23:55 UTC
E.g. 
https://tools.wmflabs.org/scholia/work/Q50813856
currently has one citation, but in the "Citations per year" graph, it says two, one of which is marked as a self-citation.

**Comment by fnielsen** [comment] 2018-08-27 11:06
Duplicate of #478

**Closed by fnielsen** 2018-08-27 11:06 UTC
Labels: P2860-cites, P50-author, P577-publication-date, SPARQL, bug, panels
