### ISSUE TITLE
On taxon landing page, provide some basic stats 

### ISSUE THREAD

**Issue by Daniel-Mietchen** [fnielsen/scholia#419] opened 2018-06-22 23:10 UTC
e.g. 
- number of taxa that are the subject of scholarly articles
- number of scholarly articles that have a taxon as their main subject
- taxa ranked by number of times they appear as main subject

**Comment by egonw** [comment] 2021-03-07 13:20
Duplicate of https://github.com/fnielsen/scholia/issues/292

**Closed by egonw** 2021-03-07 13:20 UTC
Labels: LandingPage, P921-main-subject, SPARQL, duplicate, stats
