### ISSUE TITLE
Add internationalisation and for a few languages localisation

### ISSUE THREAD

**Issue by GerardMeijssen** [fnielsen/scholia#789] opened 2019-07-22 05:50 UTC
When Scholia is available in multiple languages, it becomes relevant for scientists to add the words, the phrases in their language.
At Wikimania there has always been Siebrand always happy to help get the I18N right.

**Comment by fnielsen** [comment] 2019-07-22 19:38
Duplicate of #663

**Closed by fnielsen** 2019-07-22 19:38 UTC
Labels: internationalization, outreach, usability
